### ISSUE TITLE
Sometimes unit test 'TestNewClient_StopRefreshAtClose' has goroutine leak

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#237]
## Context

https://github.com/networkservicemesh/sdk/pull/227/checks?check_run_id=645773960

## Failure logs

```
##[error]    leaks.go:78: found unexpected goroutines:
        [Goroutine 62 in state chan send, with github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh_test.TestNewClient_StopRefreshAtClose.func1 on top of the stack:
        goroutine 62 [chan send]:
        github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh_test.TestNewClient_StopRefreshAtClose.func1(0x18d8e20, 0xc000154120, 0xc000180280, 0x0, 0x0, 0x0, 0x1180c0b, 0xc000154140, 0xc000154120)
        	/Users/runner/runners/2.169.1/work/sdk/sdk/pkg/networkservice/common/refresh/client_test.go:97 +0x78
        github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh_test.(*testRefresh).Request(0xc000010280, 0x18d8e20, 0xc000154120, 0xc000180280, 0x0, 0x0, 0x0, 0xc000154120, 0x18d21a0, 0xc000108b70)
        	/Users/runner/runners/2.169.1/work/sdk/sdk/pkg/networkservice/common/refresh/client_test.go:67 +0x96
        github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request(0xc000108b70, 0x18d8f60, 0xc000152100, 0xc000180280, 0x0, 0x0, 0x0, 0x106989c, 0xc000152100, 0xc000048c00)
        	/Users/runner/runners/2.169.1/work/sdk/sdk/pkg/networkservice/core/next/client.go:70 +0x5fb
        github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh.(*refreshClient).Request(0xc00000ee20, 0x18d8f60, 0xc000152100, 0xc000180280, 0x0, 0x0, 0x0, 0xc0001c8218, 0x1092790, 0xc0001c81c0)
        	/Users/runner/runners/2.169.1/work/sdk/sdk/pkg/networkservice/common/refresh/client.go:53 +0xaa
        github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh.(*refreshClient).createTimer.func1()
        	/Users/runner/runners/2.169.1/work/sdk/sdk/pkg/networkservice/common/refresh/client.go:96 +0x183
        created by time.goFunc
        	/Users/runner/hostedtoolcache/go/1.13.4/x64/src/time/sleep.go:168 +0x52
        ]


```

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/pull/243/checks?check_run_id=666495748

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/runs/678116601

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/pull/241/checks?check_run_id=686104163

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/pull/241/checks?check_run_id=698515870

**Comment by denis-tingajkin** [comment]
Still reproducible  https://github.com/networkservicemesh/sdk/pull/264/checks?check_run_id=724287099

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/pull/257/checks?check_run_id=729805883

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/pull/320/checks?check_run_id=785257904

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/pull/323/checks?check_run_id=790861156

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/pull/323/checks?check_run_id=790909087

**Comment by denis-tingajkin** [comment]
@edwarnicke, @haiodo Can we disable this test?

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/sdk/pull/322/checks?check_run_id=790907485

**Comment by denis-tingajkin** [comment]
@lvfxx Do you have any progress with this issue?

**Comment by denis-tingajkin** [comment]
Fixed by https://github.com/networkservicemesh/sdk/commit/2ab10a2ee11a1cc2a4f531a38b658c48c32b8f96

**Comment by denis-tingajkin** [comment]
Still reproducible https://github.com/networkservicemesh/sdk/pull/371/checks?check_run_id=844413529
