### ISSUE TITLE
HealClient produces leaks in scenario of TestNSmgrCrossNSETest  

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk#458]
## Steps to reproduce
1. Add goleak into TestNSMGR_LocalUsecase   https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/chains/nsmgr/server_test.go#L84
2. Run TestNSMGR_LocalUsecase
Actual: found leaks from the heal client 
Expected: no leaks found

## Logs
```
time="2020-09-11T17:22:42+07:00" level=error msg="Attempt to heal connection 63255ce0-c519-43b6-8aae-93667924ec56 resulted in error: rpc error: code = Canceled desc = grpc: the client connection is closing\nError returned from github.com/networkservicemesh/api/pkg/api/networkservice/networkServiceClient.Request\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:58\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:71\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/updatetoken.(*updateTokenClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/updatetoken/client.go:50\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer.(*injectPeerClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer/client.go:61\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/refresh.(*refreshClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh/client.go:55\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:144\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request.func1.1\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:171\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).eventloop.func1\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:108\ngithub.com/networkservicemesh/sdk/pkg/tools/serialize.(*Executor).AsyncExec.func3\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/tools/serialize/serialize.go:64\ngithub.com/networkservicemesh/sdk/pkg/tools/serialize.(*Executor).AsyncExec.func2\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/tools/serialize/serialize.go:55\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374" operation=github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/healClient.Request span="{}"
time="2020-09-11T17:22:42+07:00" level=info msg="==--------> github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh/refreshClient.Request() span:{}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=info msg=">><<-------- request={\"connection\":{\"id\":\"18d16852-ee0c-4d18-bffa-c380dff10af5\",\"network_service\":\"my-service\",\"context\":{\"ip_context\":{}},\"path\":{\"path_segments\":[{\"name\":\"nsc-1\",\"id\":\"1\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"nsmgr\",\"id\":\"18d16852-ee0c-4d18-bffa-c380dff10af5\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"cross-nse\",\"id\":\"524b1bc5-939f-47b5-abe1-3b0a125d9647\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"nsmgr\",\"id\":\"16fdf47c-b7dd-49f9-8750-304e7bd43467\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"final-endpoint\",\"id\":\"30e772af-8ff1-4b4e-9df3-d5e7da1d422e\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}}]}},\"mechanism_preferences\":[{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\"}]} span={}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=info msg="==----------> github.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer/injectPeerClient.Request() span:{}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=info msg=">><<---------- request={\"connection\":{\"id\":\"18d16852-ee0c-4d18-bffa-c380dff10af5\",\"network_service\":\"my-service\",\"context\":{\"ip_context\":{}},\"path\":{\"path_segments\":[{\"name\":\"nsc-1\",\"id\":\"1\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"nsmgr\",\"id\":\"18d16852-ee0c-4d18-bffa-c380dff10af5\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"cross-nse\",\"id\":\"524b1bc5-939f-47b5-abe1-3b0a125d9647\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"nsmgr\",\"id\":\"16fdf47c-b7dd-49f9-8750-304e7bd43467\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"final-endpoint\",\"id\":\"30e772af-8ff1-4b4e-9df3-d5e7da1d422e\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}}]}},\"mechanism_preferences\":[{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\"}]} span={}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=info msg="==------------> github.com/networkservicemesh/sdk/pkg/networkservice/common/updatetoken/updateTokenClient.Request() span:{}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=info msg=">><<------------ request={\"connection\":{\"id\":\"18d16852-ee0c-4d18-bffa-c380dff10af5\",\"network_service\":\"my-service\",\"context\":{\"ip_context\":{}},\"path\":{\"path_segments\":[{\"name\":\"nsc-1\",\"id\":\"1\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"nsmgr\",\"id\":\"18d16852-ee0c-4d18-bffa-c380dff10af5\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"cross-nse\",\"id\":\"524b1bc5-939f-47b5-abe1-3b0a125d9647\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"nsmgr\",\"id\":\"16fdf47c-b7dd-49f9-8750-304e7bd43467\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"final-endpoint\",\"id\":\"30e772af-8ff1-4b4e-9df3-d5e7da1d422e\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}}]}},\"mechanism_preferences\":[{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\"}]} span={}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=info msg="==--------------> github.com/networkservicemesh/api/pkg/api/networkservice/networkServiceClient.Request() span:{}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=info msg=">><<-------------- request={\"connection\":{\"id\":\"18d16852-ee0c-4d18-bffa-c380dff10af5\",\"network_service\":\"my-service\",\"context\":{\"ip_context\":{}},\"path\":{\"path_segments\":[{\"name\":\"nsc-1\",\"id\":\"1\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"nsmgr\",\"id\":\"18d16852-ee0c-4d18-bffa-c380dff10af5\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"cross-nse\",\"id\":\"524b1bc5-939f-47b5-abe1-3b0a125d9647\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"nsmgr\",\"id\":\"16fdf47c-b7dd-49f9-8750-304e7bd43467\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}},{\"name\":\"final-endpoint\",\"id\":\"30e772af-8ff1-4b4e-9df3-d5e7da1d422e\",\"token\":\"TestToken\",\"expires\":{\"seconds\":32503683661,\"nanos\":1}}]}},\"mechanism_preferences\":[{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\"}]} span={}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=error msg=">><<-------------- error=rpc error: code = Canceled desc = grpc: the client connection is closing\nError returned from github.com/networkservicemesh/api/pkg/api/networkservice/networkServiceClient.Request\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:58\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:71\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/updatetoken.(*updateTokenClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/updatetoken/client.go:50\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer.(*injectPeerClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer/client.go:61\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/refresh.(*refreshClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh/client.go:55\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:144\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request.func1.1\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:171\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).eventloop.func1\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:108\ngithub.com/networkservicemesh/sdk/pkg/tools/serialize.(*Executor).AsyncExec.func3\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/tools/serialize/serialize.go:64\ngithub.com/networkservicemesh/sdk/pkg/tools/serialize.(*Executor).AsyncExec.func2\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/tools/serialize/serialize.go:55\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374 span={}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=error msg=">><<------------ error=Error returned from github.com/networkservicemesh/api/pkg/api/networkservice/networkServiceClient.Request: rpc error: code = Canceled desc = grpc: the client connection is closing span={}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=error msg=">><<---------- error=Error returned from github.com/networkservicemesh/api/pkg/api/networkservice/networkServiceClient.Request: rpc error: code = Canceled desc = grpc: the client connection is closing span={}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=error msg=">><<-------- error=Error returned from github.com/networkservicemesh/api/pkg/api/networkservice/networkServiceClient.Request: rpc error: code = Canceled desc = grpc: the client connection is closing span={}" cmd=/tmp/___TestNSmgrCrossNSETest_in_github_com_networkservicemesh_sdk_pkg_networkservice_chains_nsmgr__5_
time="2020-09-11T17:22:42+07:00" level=error msg="Attempt to heal connection 18d16852-ee0c-4d18-bffa-c380dff10af5 resulted in error: rpc error: code = Canceled desc = grpc: the client connection is closing\nError returned from github.com/networkservicemesh/api/pkg/api/networkservice/networkServiceClient.Request\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:58\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:71\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/updatetoken.(*updateTokenClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/updatetoken/client.go:50\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer.(*injectPeerClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer/client.go:61\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/refresh.(*refreshClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh/client.go:55\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*traceClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/trace/client.go:54\ngithub.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/core/next/client.go:69\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:144\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request.func1.1\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:171\ngithub.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).eventloop.func1\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:108\ngithub.com/networkservicemesh/sdk/pkg/tools/serialize.(*Executor).AsyncExec.func3\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/tools/serialize/serialize.go:64\ngithub.com/networkservicemesh/sdk/pkg/tools/serialize.(*Executor).AsyncExec.func2\n\t/home/user/go/src/github.com/networkservicemesh/sdk/pkg/tools/serialize/serialize.go:55\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374" operation=github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/healClient.Request span="{}"
    leaks.go:78: found unexpected goroutines:
        [Goroutine 244 in state semacquire, with sync.runtime_SemacquireMutex on top of the stack:
        goroutine 244 [semacquire]:
        sync.runtime_SemacquireMutex(0xc00048a538, 0xb1c700, 0x1)
        	/usr/local/go/src/runtime/sema.go:71 +0x47
        sync.(*Mutex).lockSlow(0xc00048a534)
        	/usr/local/go/src/sync/mutex.go:138 +0x105
        sync.(*Mutex).Lock(...)
        	/usr/local/go/src/sync/mutex.go:81
        sync.(*Once).doSlow(0xc00048a530, 0xc00034a0e0)
        	/usr/local/go/src/sync/once.go:62 +0x105
        sync.(*Once).Do(0xc00048a530, 0xc00034a0e0)
        	/usr/local/go/src/sync/once.go:57 +0x45
        created by github.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).monitorLoop
        	/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:80 +0x7a
        
         Goroutine 12 in state runnable, with google.golang.org/grpc.defaultCallInfo on top of the stack:
        goroutine 12 [runnable]:
        google.golang.org/grpc.defaultCallInfo(...)
        	/home/user/go/pkg/mod/google.golang.org/grpc@v1.30.0/rpc_util.go:167
        google.golang.org/grpc.newClientStream(0xcc8200, 0xc00018e010, 0x10c1240, 0xc00030f180, 0xc0eb4a, 0x30, 0xc00023d6a0, 0x2, 0x2, 0x0, ...)
        	/home/user/go/pkg/mod/google.golang.org/grpc@v1.30.0/stream.go:166 +0x99
        google.golang.org/grpc.(*ClientConn).NewStream(0xc00030f180, 0xcc8200, 0xc00018e010, 0x10c1240, 0xc0eb4a, 0x30, 0xc00048ec80, 0x1, 0x1, 0x40d20f, ...)
        	/home/user/go/pkg/mod/google.golang.org/grpc@v1.30.0/stream.go:149 +0x17f
        github.com/networkservicemesh/api/pkg/api/networkservice.(*monitorConnectionClient).MonitorConnections(0xc00048e100, 0xcc8200, 0xc00018e010, 0xc0002c3b00, 0xc00048ec80, 0x1, 0x1, 0x0, 0x0, 0xcb9d80, ...)
        	/home/user/go/pkg/mod/github.com/networkservicemesh/api@v0.0.0-20200813164503-9585b38e6772/pkg/api/networkservice/connection.pb.go:535 +0xba
        github.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).monitorLoop.func1()
        	/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:87 +0x138
        sync.(*Once).doSlow(0xc00048a530, 0xc0003b4db0)
        	/usr/local/go/src/sync/once.go:66 +0xec
        sync.(*Once).Do(0xc00048a530, 0xc0003b4db0)
        	/usr/local/go/src/sync/once.go:57 +0x45
        created by github.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).monitorLoop
        	/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:80 +0x7a
        
         Goroutine 92 in state syscall, with syscall.Syscall6 on top of the stack:
        goroutine 92 [syscall]:
        syscall.Syscall6(0xe8, 0x11, 0xc00070fb6c, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
        golang.org/x/sys/unix.EpollWait(0x11, 0xc00070fb6c, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        	/home/user/go/pkg/mod/golang.org/x/sys@v0.0.0-20200610111108-226ff32320da/unix/zsyscall_linux_amd64.go:76 +0x72
        github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc0001c8640, 0x0, 0x0, 0x0)
        	/home/user/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/inotify_poller.go:86 +0x91
        github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0001c26e0)
        	/home/user/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/inotify.go:192 +0x206
        created by github.com/fsnotify/fsnotify.NewWatcher
        	/home/user/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/inotify.go:59 +0x1a8
        
         Goroutine 294 in state semacquire, with sync.runtime_SemacquireMutex on top of the stack:
        goroutine 294 [semacquire]:
        sync.runtime_SemacquireMutex(0xc00048a538, 0xc000432300, 0x1)
        	/usr/local/go/src/runtime/sema.go:71 +0x47
        sync.(*Mutex).lockSlow(0xc00048a534)
        	/usr/local/go/src/sync/mutex.go:138 +0x105
        sync.(*Mutex).Lock(...)
        	/usr/local/go/src/sync/mutex.go:81
        sync.(*Once).doSlow(0xc00048a530, 0xc00027a240)
        	/usr/local/go/src/sync/once.go:62 +0x105
        sync.(*Once).Do(0xc00048a530, 0xc00027a240)
        	/usr/local/go/src/sync/once.go:57 +0x45
        created by github.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).monitorLoop
        	/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:80 +0x7a
        
         Goroutine 45 in state semacquire, with sync.runtime_SemacquireMutex on top of the stack:
        goroutine 45 [semacquire]:
        sync.runtime_SemacquireMutex(0xc00048a538, 0x0, 0x1)
        	/usr/local/go/src/runtime/sema.go:71 +0x47
        sync.(*Mutex).lockSlow(0xc00048a534)
        	/usr/local/go/src/sync/mutex.go:138 +0x105
        sync.(*Mutex).Lock(...)
        	/usr/local/go/src/sync/mutex.go:81
        sync.(*Once).doSlow(0xc00048a530, 0xc00068ee10)
        	/usr/local/go/src/sync/once.go:62 +0x105
        sync.(*Once).Do(0xc00048a530, 0xc00068ee10)
        	/usr/local/go/src/sync/once.go:57 +0x45
        created by github.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).monitorLoop
        	/home/user/go/src/github.com/networkservicemesh/sdk/pkg/networkservice/common/heal/client.go:80 +0x7a
        ]
--- FAIL: TestNSmgrCrossNSETest (0.47s)
FAIL

Process finished with exit code 1

```

**Comment by denis-tingajkin** [comment]
Fixed by https://github.com/networkservicemesh/sdk/commit/5b64906a352b8b04a60e5eaf386a4d59a4bbe58d and covered by https://github.com/networkservicemesh/sdk/commit/feac848419675a09d86b95bdf66d5e325ad43fbe
