### ISSUE TITLE
`TestNSMGR_RemoteUsecase_BusyEndpoints` has goroutine leaks sometimes

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#619]
https://github.com/networkservicemesh/sdk/pull/612/checks?check_run_id=1508552180
```
--- FAIL: TestNSMGR_RemoteUsecase_BusyEndpoints (1.33s)
Error:     leaks.go:78: found unexpected goroutines:
        [Goroutine 638 in state chan send, with github.com/networkservicemesh/api/pkg/api/registry.ReadNetworkServiceChannel.func1 on top of the stack:
        goroutine 638 [chan send]:
        github.com/networkservicemesh/api/pkg/api/registry.ReadNetworkServiceChannel.func1(0x11b1760, 0xc0003ff440, 0xc00067e5a0)
        	/home/runner/go/pkg/mod/github.com/networkservicemesh/api@v0.0.0-20201204203731-4294f67deaa4/pkg/api/registry/helpers.go:54 +0x7a
        created by github.com/networkservicemesh/api/pkg/api/registry.ReadNetworkServiceChannel
        	/home/runner/go/pkg/mod/github.com/networkservicemesh/api@v0.0.0-20201204203731-4294f67deaa4/pkg/api/registry/helpers.go:52 +0x85
        ]
```

**Comment by Bolodya1997** [comment]
Seems like it is not an issue with test, but some issue with discover/watch:
https://github.com/networkservicemesh/sdk/pull/671/checks?check_run_id=1767112466
```
--- FAIL: TestNSMGR_PassThroughLocal (1.67s)
Error:     leaks.go:78: found unexpected goroutines:
        [Goroutine 9393 in state chan send, with github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*networkServiceEndpointRegistryServer).sendEvent.func1 on top of the stack:
        goroutine 9393 [chan send]:
        github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*networkServiceEndpointRegistryServer).sendEvent.func1()
        	D:/a/sdk/sdk/pkg/registry/common/memory/nse_server.go:129 +0x10f
        github.com/edwarnicke/serialize.(*Executor).process(0xc002754208, 0xc000bd6c40)
        	C:/Users/runneradmin/go/pkg/mod/github.com/edwarnicke/serialize@v1.0.7/serialize.go:86 +0x1d9
        created by github.com/edwarnicke/serialize.(*Executor).AsyncExec
        	C:/Users/runneradmin/go/pkg/mod/github.com/edwarnicke/serialize@v1.0.7/serialize.go:56 +0x2e5
        ]
```
https://github.com/networkservicemesh/sdk/pull/671/checks?check_run_id=1763674634
```
--- FAIL: TestNSMGR_SelectsRestartingEndpoint (2.57s)
Error:     leaks.go:78: found unexpected goroutines:
        [Goroutine 2859 in state chan send, with github.com/networkservicemesh/api/pkg/api/registry.ReadNetworkServiceEndpointChannel.func1 on top of the stack:
        goroutine 2859 [chan send]:
        github.com/networkservicemesh/api/pkg/api/registry.ReadNetworkServiceEndpointChannel.func1(0x1dc44a0, 0xc000098d40, 0xc00058e600)
        	/Users/runner/go/pkg/mod/github.com/networkservicemesh/api@v0.0.0-20210112152104-45029fb10e27/pkg/api/registry/helpers.go:66 +0x7a
        created by github.com/networkservicemesh/api/pkg/api/registry.ReadNetworkServiceEndpointChannel
        	/Users/runner/go/pkg/mod/github.com/networkservicemesh/api@v0.0.0-20210112152104-45029fb10e27/pkg/api/registry/helpers.go:64 +0x85
        ]
```
