### ISSUE TITLE
unit test Test_QueryCacheServer_ShouldCleanupGoroutinesOnNSEUnregister have goroutines leak

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#728]
Related to https://github.com/networkservicemesh/sdk/commit/20d510498cab80f1edfc44462da56403cd700f6b

## Logs
```
 Test_QueryCacheServer_ShouldCleanupGoroutinesOnNSEUnregister (0.46s)
Error:     leaks.go:78: found unexpected goroutines:
        [Goroutine 55 in state chan receive, with github.com/networkservicemesh/sdk/pkg/registry/core/streamchannel.(*networkServiceEndpointRegistryFindClient).Recv on top of the stack:
        goroutine 55 [chan receive]:
        github.com/networkservicemesh/sdk/pkg/registry/core/streamchannel.(*networkServiceEndpointRegistryFindClient).Recv(0xc000069dc0, 0x1987000, 0xc000069d80, 0xc0004dc900)
        	D:/a/sdk/sdk/pkg/registry/core/streamchannel/nse_registry_stream_channel.go:45 +0x75
        github.com/networkservicemesh/sdk/pkg/registry/common/querycache.(*queryCacheNSEClient).Find.func1(0xc0004dc7c0, 0xc0004f83f0, 0x27, 0xc0004dc900, 0x19870c0, 0xc0004d6ff0, 0x0, 0x0, 0x0)
        	D:/a/sdk/sdk/pkg/registry/common/querycache/nse_client.go:87 +0x205
        created by github.com/networkservicemesh/sdk/pkg/registry/common/querycache.(*queryCacheNSEClient).Find
        	D:/a/sdk/sdk/pkg/registry/common/querycache/nse_client.go:74 +0x4db
        
         Goroutine 40 in state select, with github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).receiveEvent on top of the stack:
        goroutine 40 [select]:
        github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).receiveEvent(0xc0004f2480, 0xc0004dc900, 0x198b7e0, 0xc00007c8e0, 0xc000077260, 0xc000097d44, 0x5)
        	D:/a/sdk/sdk/pkg/registry/common/memory/nse_server.go:141 +0x12f
        github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).Find(0xc0004f2480, 0xc0004dc900, 0x198b7e0, 0xc00007c8e0, 0x0, 0x0)
        	D:/a/sdk/sdk/pkg/registry/common/memory/nse_server.go:101 +0x367
        github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceEndpointRegistryServer).Find(0xc00007eae0, 0xc0004dc900, 0x198b780, 0xc00007eb10, 0xc000097e18, 0x5)
        	D:/a/sdk/sdk/pkg/registry/core/next/nse_registry_server.go:62 +0x3ce
        github.com/networkservicemesh/sdk/pkg/registry/core/adapters.nseFindServerToClient.func1(0xc000077200, 0x1986480, 0xc00007eae0, 0xc0004dc900, 0x198b780, 0xc00007eb10)
        	D:/a/sdk/sdk/pkg/registry/core/adapters/nse_registry.go:128 +0xbb
        created by github.com/networkservicemesh/sdk/pkg/registry/core/adapters.nseFindServerToClient
        	D:/a/sdk/sdk/pkg/registry/core/adapters/nse_registry.go:126 +0x1b5
```

## Build

https://github.com/networkservicemesh/sdk/runs/1962975943

**Comment by denis-tingaikin** [comment]
https://github.com/networkservicemesh/sdk/pull/730/checks?check_run_id=1970417907
