### ISSUE TITLE
Goleaks while using opentelemetry

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk#744]
<h3>Description</h3>

If we start opentelemetry instead of opentracing, there will be goleaks in sandbox tests.

The problem occurs if there is refresh request in test. It was found that there are goleaks after `MonitorConnections` calls from the first `nsc.Requst()`. It may also be related to incorrect `opentelemetry.StreamClientInterceptor `behavior.

<h3>Logs</h3>

```
=== RUN   TestNSMGR_LocalUsecase
    leaks.go:78: found unexpected goroutines:
        [Goroutine 174 in state chan receive, with go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.wrapClientStream.func1 on top of the stack:
        goroutine 174 [chan receive]:
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.wrapClientStream.func1(0xc00069e960, 0xc00069e900, 0xc00069e9c0)
        	/home/art/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.17.1-0.20210222002102-f011c951891d/interceptor.go:214 +0xb7
        created by go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.wrapClientStream
        	/home/art/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.17.1-0.20210222002102-f011c951891d/interceptor.go:208 +0xc9
        
         Goroutine 175 in state chan receive, with go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamClientInterceptor.func1.1 on top of the stack:
        goroutine 175 [chan receive]:
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamClientInterceptor.func1.1(0xc00042bd00, 0x15163e0, 0x1b21fa8)
        	/home/art/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.17.1-0.20210222002102-f011c951891d/interceptor.go:290 +0x85
        created by go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamClientInterceptor.func1
        	/home/art/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.17.1-0.20210222002102-f011c951891d/interceptor.go:289 +0xac6

```

<h3>Steps to reproduce</h3>

1. Enable opentelemetry
2. Run sandbox test, where refresh request is simulated (ex. `TestNSMGR_LocalUsecase`)
3. Goleaks

**Comment by glazychev-art** [comment]
opentelemetry support  - #628

**Comment by glazychev-art** [comment]
Done: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/839
