### ISSUE TITLE
TestConnectServer_RequestParallel is not stable

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#755]
```
2021-03-05T07:01:40.5038110Z --- FAIL: TestConnectServer_RequestParallel (4.60s)
2021-03-05T07:01:40.5042250Z     server_test.go:304: 
2021-03-05T07:01:40.5042770Z         	Error Trace:	server_test.go:304
2021-03-05T07:01:40.5043240Z         	            				asm_amd64.s:1374
2021-03-05T07:01:40.5043740Z         	Error:      	Received unexpected error:
2021-03-05T07:01:40.5044300Z         	            	context deadline exceeded
2021-03-05T07:01:40.5044960Z         	Test:       	TestConnectServer_RequestParallel
2021-03-05T07:01:40.5045590Z     server_test.go:304: 
2021-03-05T07:01:40.5046050Z         	Error Trace:	server_test.go:304
2021-03-05T07:01:40.5046500Z         	            				asm_amd64.s:1374
2021-03-05T07:01:40.5047010Z         	Error:      	Received unexpected error:
2021-03-05T07:01:40.5047570Z         	            	context deadline exceeded
2021-03-05T07:01:40.5048680Z         	Test:       	TestConnectServer_RequestParallel
...
...
...
2021-03-05T07:01:42.0394020Z         	Error Trace:	server_test.go:304
2021-03-05T07:01:42.0394470Z         	            				asm_amd64.s:1374
2021-03-05T07:01:42.0394970Z         	Error:      	Received unexpected error:
2021-03-05T07:01:42.0395520Z         	            	context deadline exceeded
2021-03-05T07:01:42.0396300Z         	Test:       	TestConnectServer_RequestParallel
2021-03-05T07:01:42.0396890Z     server_test.go:329: 
2021-03-05T07:01:42.0397340Z         	Error Trace:	server_test.go:329
2021-03-05T07:01:42.0397790Z         	Error:      	Not equal: 
2021-03-05T07:01:42.0398210Z         	            	expected: 1000
2021-03-05T07:01:42.0398610Z         	            	actual  : 0
2021-03-05T07:01:42.0399170Z         	Test:       	TestConnectServer_RequestParallel
2021-03-05T07:01:42.0405920Z ##[error]    leaks.go:78: found unexpected goroutines:
2021-03-05T07:01:42.0419560Z         [Goroutine 15 in state semacquire, with sync.runtime_Semacquire on top of the stack:
2021-03-05T07:01:42.0420280Z         goroutine 15 [semacquire]:
2021-03-05T07:01:42.0420820Z         sync.runtime_Semacquire(0xc0000c5158)
2021-03-05T07:01:42.0421540Z         	/Users/runner/hostedtoolcache/go/1.15.8/x64/src/runtime/sema.go:56 +0x45
2021-03-05T07:01:42.0422170Z         sync.(*WaitGroup).Wait(0xc0000c5150)
2021-03-05T07:01:42.0422890Z         	/Users/runner/hostedtoolcache/go/1.15.8/x64/src/sync/waitgroup.go:130 +0xe5
2021-03-05T07:01:42.0427690Z         github.com/networkservicemesh/sdk/pkg/networkservice/common/connect_test.TestConnectServer_RequestParallel.func2(0x1919560, 0xc0003801b0, 0xc000364bd0, 0xc00031d080, 0xc0000c5140, 0xc0000c5150, 0x191fee0, 0xc00037e980, 0x26a)
2021-03-05T07:01:42.0429200Z         	/Users/runner/work/sdk/sdk/pkg/networkservice/common/connect/server_test.go:309 +0x2e5
2021-03-05T07:01:42.0430480Z         created by github.com/networkservicemesh/sdk/pkg/networkservice/common/connect_test.TestConnectServer_RequestParallel
2021-03-05T07:01:42.0431690Z         	/Users/runner/work/sdk/sdk/pkg/networkservice/common/connect/server_test.go:292 +0x796
2021-03-05T07:01:42.0432240Z         
2021-03-05T07:01:42.0432900Z          Goroutine 723 in state semacquire, with sync.runtime_Semacquire on top of the stack:
2021-03-05T07:01:42.0433590Z         goroutine 723 [semacquire]:
2021-03-05T07:01:42.0434130Z         sync.runtime_Semacquire(0xc0000c5158)
2021-03-05T07:01:42.0434850Z         	/Users/runner/hostedtoolcache/go/1.15.8/x64/src/runtime/sema.go:56 +0x45
2021-03-05T07:01:42.0435480Z         sync.(*WaitGroup).Wait(0xc0000c5150)
2021-03-05T07:01:42.0436180Z         	/Users/runner/hostedtoolcache/go/1.15.8/x64/src/sync/waitgroup.go:130 +0xe5
2021-03-05T07:01:42.0437760Z         github.com/networkservicemesh/sdk/pkg/networkservice/common/connect_test.TestConnectServer_RequestParallel.func2(0x1919560, 0xc0003801b0, 0xc000364bd0, 0xc00031d080, 0xc0000c5140, 0xc0000c5150, 0x191fee0, 0xc00037e980, 0x26d)
2021-03-05T07:01:42.0439310Z         	/Users/runner/work/sdk/sdk/pkg/networkservice/common/connect/server_test.go:309 +0x2e5
2021-03-05T07:01:42.0440530Z         created by github.com/networkservicemesh/sdk/pkg/networkservice/common/connect_test.TestConnectServer_RequestParallel
2021-03-05T07:01:42.0441710Z         	/Users/runner/work/sdk/sdk/pkg/networkservice/common/connect/server_test.go:292 +0x796
...
...
...
2021-03-05T07:01:50.2159540Z          Goroutine 1101 in state semacquire, with sync.runtime_Semacquire on top of the stack:
2021-03-05T07:01:50.2160190Z         goroutine 1101 [semacquire]:
2021-03-05T07:01:50.2160720Z         sync.runtime_Semacquire(0xc0000c5158)
2021-03-05T07:01:50.2161530Z         	/Users/runner/hostedtoolcache/go/1.15.8/x64/src/runtime/sema.go:56 +0x45
2021-03-05T07:01:50.2162200Z         sync.(*WaitGroup).Wait(0xc0000c5150)
2021-03-05T07:01:50.2162870Z         	/Users/runner/hostedtoolcache/go/1.15.8/x64/src/sync/waitgroup.go:130 +0xe5
2021-03-05T07:01:50.2164410Z         github.com/networkservicemesh/sdk/pkg/networkservice/common/connect_test.TestConnectServer_RequestParallel.func2(0x1919560, 0xc0003801b0, 0xc000364bd0, 0xc00031d080, 0xc0000c5140, 0xc0000c5150, 0x191fee0, 0xc00037e980, 0x3e7)
2021-03-05T07:01:50.2165820Z         	/Users/runner/work/sdk/sdk/pkg/networkservice/common/connect/server_test.go:309 +0x2e5
2021-03-05T07:01:50.2167040Z         created by github.com/networkservicemesh/sdk/pkg/networkservice/common/connect_test.TestConnectServer_RequestParallel
2021-03-05T07:01:50.2168220Z         	/Users/runner/work/sdk/sdk/pkg/networkservice/common/connect/server_test.go:292 +0x796
2021-03-05T07:01:50.2168760Z         ]
2021-03-05T07:01:50.2169090Z No logger in context
2021-03-05T07:01:50.2169480Z No logger in context
2021-03-05T07:01:50.2169860Z No logger in context
2021-03-05T07:01:50.2170240Z No logger in context
2021-03-05T07:01:50.2170560Z FAIL
2021-03-05T07:01:50.2171220Z FAIL	github.com/networkservicemesh/sdk/pkg/networkservice/common/connect	5.619s
```

**Comment by Bolodya1997** [comment]
**Update:** https://github.com/networkservicemesh/sdk/pull/756/checks?check_run_id=2065837561
This is due to the garbage collector STW:
```
2021-03-09T10:57:38.6615614Z -- BEGIN:  35.217 # tests start [~0.009s since process start]
2021-03-09T10:57:38.6616575Z gc 1 @0.009s 0%: 0.041+0.34+0.002 ms clock, 0.083+0/0.045/0.27+0.005 ms cpu, 1->1->0 MB, 4 MB goal, 2 P (forced)
2021-03-09T10:57:38.6617610Z -- START: 35.231 # TestConnectServer_Request dial A start [0.023]
2021-03-09T10:57:38.6618285Z -- DIAL:  35.233 : 1.774011ms # dial A end [0.025]
2021-03-09T10:57:38.6618931Z -- START: 35.236 # dial B start [0.028]
2021-03-09T10:57:38.6619561Z -- DIAL:  35.238 : 1.59751ms # dial B end [0.030]
2021-03-09T10:57:38.6620188Z -- START: 35.256 # TestConnectServer_RequestParallel dial A start [0.048]
2021-03-09T10:57:38.6620828Z -- DIAL:  35.357 : 101.225318ms # dial A end [0.149]
2021-03-09T10:57:38.6621687Z gc 2 @0.051s 57%: 92+12+0.018 ms clock, 184+1.8/1.2/0+0.036 ms cpu, 4->4->1 MB, 5 MB goal, 2 P
...
2021-03-09T10:57:38.6640706Z --- FAIL: TestConnectServer_RequestParallel (2.00s)
```
TestConnectServer_RequestParallel dial A [0.048 - 0.149] overlaps with gc 2 [0.051 - 0.155] and so it is the reason for 100+ ms dial timeout failure.
