### ISSUE TITLE
Heal tests fail when called in sequence

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/sdk#855]
## Expected Behavior

If a test is passing when called alone, it should also pass when called 2 (or more) times in sequence.
Calling tests several times can help find unstable tests.

## Current Behavior

When a test function calls 2 other test function, second test always fails.

## Failure Information (for bugs)

Many unexpected stalled goroutines are found during cleanup. See logs below for details.

## Steps to Reproduce

In `pkg/networkservice/chains/nsmgr/server_heal_test.go` add and run the following test:
```go
func Test(t *testing.T) {
	TestNSMGR_HealEndpoint(t)
	TestNSMGR_HealEndpoint(t)
}
```
Test will fail despite that `TestNSMGR_HealEndpoint` works when executed separately.

## Failure Logs

<details>

    leaks.go:78: found unexpected goroutines:
        [Goroutine 9 in state select, with google.golang.org/grpc.(*ccBalancerWrapper).watcher on top of the stack:
        goroutine 9 [select]:
        google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00007fac0)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/balancer_conn_wrappers.go:69 +0xbb
        created by google.golang.org/grpc.newCCBalancerWrapper
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/balancer_conn_wrappers.go:60 +0x17a
        
         Goroutine 10 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
        goroutine 10 [IO wait]:
        internal/poll.runtime_pollWait(0x1e166845f68, 0x77, 0x19c8220)
        	C:/Program Files/Go/src/runtime/netpoll.go:222 +0x65
        internal/poll.(*pollDesc).wait(0xc0002a4438, 0x77, 0xc000310c00, 0x0, 0x0)
        	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
        internal/poll.execIO(0xc0002a4368, 0x1908fa8, 0x20, 0xc000069b00, 0x10c03e5)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x113
        internal/poll.(*FD).ConnectEx(0xc0002a4280, 0x19c7380, 0xc000122000, 0xc000841b00, 0xc0002a4280)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:800 +0x6a
        net.(*netFD).connect(0xc0002a4280, 0x19d5a58, 0xc000841b00, 0x0, 0x0, 0x19c7380, 0xc000122000, 0x0, 0x0, 0x0, ...)
        	C:/Program Files/Go/src/net/fd_windows.go:106 +0x210
        net.(*netFD).dial(0xc0002a4280, 0x19d5a58, 0xc000841b00, 0x19d9a38, 0x0, 0x19d9a38, 0xc000760090, 0x0, 0x1ef7010, 0x10)
        	C:/Program Files/Go/src/net/sock_posix.go:149 +0x112
        net.socket(0x19d5a58, 0xc000841b00, 0x18d345c, 0x3, 0x2, 0x1, 0x0, 0x0, 0x19d9a38, 0x0, ...)
        	C:/Program Files/Go/src/net/sock_posix.go:70 +0x1f0
        net.internetSocket(0x19d5a58, 0xc000841b00, 0x18d345c, 0x3, 0x19d9a38, 0x0, 0x19d9a38, 0xc000760090, 0x1, 0x0, ...)
        	C:/Program Files/Go/src/net/ipsock_posix.go:141 +0x170
        net.(*sysDialer).doDialTCP(0xc00023e180, 0x19d5a58, 0xc000841b00, 0x0, 0xc000760090, 0x17ce980, 0x1ef6cf0, 0x0)
        	C:/Program Files/Go/src/net/tcpsock_posix.go:65 +0xc9
        net.(*sysDialer).dialTCP(0xc00023e180, 0x19d5a58, 0xc000841b00, 0x0, 0xc000760090, 0xc000674d88, 0xf35de5, 0x60)
        	C:/Program Files/Go/src/net/tcpsock_posix.go:61 +0xde
        net.(*sysDialer).dialSingle(0xc00023e180, 0x19d5a58, 0xc000841b00, 0x19cdaf0, 0xc000760090, 0x0, 0x0, 0x0, 0x0)
        	C:/Program Files/Go/src/net/dial.go:580 +0x5e8
        net.(*sysDialer).dialSerial(0xc00023e180, 0x19d5a58, 0xc000841b00, 0xc000916f90, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        	C:/Program Files/Go/src/net/dial.go:548 +0x16b
        net.(*Dialer).DialContext(0xc000675078, 0x19d5a58, 0xc000841b00, 0x18d345c, 0x3, 0xc00024a3d0, 0xf, 0x0, 0x0, 0x0, ...)
        	C:/Program Files/Go/src/net/dial.go:425 +0x705
        google.golang.org/grpc/internal/transport.proxyDial(0x19d5a58, 0xc000841b00, 0xc00024a3d0, 0xf, 0x18dbd3c, 0xe, 0xf3eb89, 0xc000916f70, 0x10, 0x10)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/proxy.go:125 +0x105
        google.golang.org/grpc/internal/transport.dial(0x19d5a58, 0xc000841b00, 0x0, 0xc00024a3d0, 0xf, 0xc00024a3d0, 0xf, 0x0, 0x0, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/http2_client.go:160 +0x338
        google.golang.org/grpc/internal/transport.newHTTP2Client(0x19d5a58, 0xc000841b00, 0x19d59e8, 0xc00007f980, 0xc00024a3d0, 0xf, 0xc00024a3d0, 0xf, 0x0, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/http2_client.go:193 +0x17a
        google.golang.org/grpc/internal/transport.NewClientTransport(...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/transport.go:579
        google.golang.org/grpc.(*addrConn).createTransport(0xc0000f1600, 0xc00024a3d0, 0xf, 0xc00024a3d0, 0xf, 0x0, 0x0, 0x0, 0x0, 0x18dbd3c, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1322 +0x411
        google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc0000f1600, 0xc00007fa40, 0x1, 0x1, 0xc0181a7db9514d3c, 0x4e83dbf0d, 0x1ea6b00, 0x19de448, 0xc000156000, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1252 +0x36c
        google.golang.org/grpc.(*addrConn).resetTransport(0xc0000f1600)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1167 +0x285
        created by google.golang.org/grpc.(*addrConn).connect
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:843 +0x13b
        
         Goroutine 153 in state select, with net.(*netFD).connect.func2 on top of the stack:
        goroutine 153 [select]:
        net.(*netFD).connect.func2(0x19d5a58, 0xc0006560c0, 0xc000856780, 0xc0005a8600)
        	C:/Program Files/Go/src/net/fd_windows.go:95 +0x8e
        created by net.(*netFD).connect
        	C:/Program Files/Go/src/net/fd_windows.go:94 +0x1e5
        
         Goroutine 899 in state select, with net.(*netFD).connect.func2 on top of the stack:
        goroutine 899 [select]:
        net.(*netFD).connect.func2(0x19d5a58, 0xc000288c00, 0xc000246000, 0xc000304300)
        	C:/Program Files/Go/src/net/fd_windows.go:95 +0x8e
        created by net.(*netFD).connect
        	C:/Program Files/Go/src/net/fd_windows.go:94 +0x1e5
        
         Goroutine 53 in state select, with google.golang.org/grpc.(*ccBalancerWrapper).watcher on top of the stack:
        goroutine 53 [select]:
        google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00028a440)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/balancer_conn_wrappers.go:69 +0xbb
        created by google.golang.org/grpc.newCCBalancerWrapper
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/balancer_conn_wrappers.go:60 +0x17a
        
         Goroutine 54 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
        goroutine 54 [IO wait]:
        internal/poll.runtime_pollWait(0x1e166846138, 0x77, 0x19c8220)
        	C:/Program Files/Go/src/runtime/netpoll.go:222 +0x65
        internal/poll.(*pollDesc).wait(0xc000856938, 0x77, 0xc000a32200, 0x0, 0x0)
        	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
        internal/poll.execIO(0xc000856868, 0x1908fa8, 0x20, 0xc000284600, 0x10c03e5)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x113
        internal/poll.(*FD).ConnectEx(0xc000856780, 0x19c7380, 0xc000438060, 0xc0006560c0, 0xc000856780)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:800 +0x6a
        net.(*netFD).connect(0xc000856780, 0x19d5a58, 0xc0006560c0, 0x0, 0x0, 0x19c7380, 0xc000438060, 0x0, 0x0, 0x0, ...)
        	C:/Program Files/Go/src/net/fd_windows.go:106 +0x210
        net.(*netFD).dial(0xc000856780, 0x19d5a58, 0xc0006560c0, 0x19d9a38, 0x0, 0x19d9a38, 0xc0005a2c90, 0x0, 0x1ef7010, 0x10)
        	C:/Program Files/Go/src/net/sock_posix.go:149 +0x112
        net.socket(0x19d5a58, 0xc0006560c0, 0x18d345c, 0x3, 0x2, 0x1, 0x0, 0x0, 0x19d9a38, 0x0, ...)
        	C:/Program Files/Go/src/net/sock_posix.go:70 +0x1f0
        net.internetSocket(0x19d5a58, 0xc0006560c0, 0x18d345c, 0x3, 0x19d9a38, 0x0, 0x19d9a38, 0xc0005a2c90, 0x1, 0x0, ...)
        	C:/Program Files/Go/src/net/ipsock_posix.go:141 +0x170
        net.(*sysDialer).doDialTCP(0xc0007ce000, 0x19d5a58, 0xc0006560c0, 0x0, 0xc0005a2c90, 0x17ce980, 0x1ef6cf0, 0x0)
        	C:/Program Files/Go/src/net/tcpsock_posix.go:65 +0xc9
        net.(*sysDialer).dialTCP(0xc0007ce000, 0x19d5a58, 0xc0006560c0, 0x0, 0xc0005a2c90, 0xc000670d88, 0xf35de5, 0x60)
        	C:/Program Files/Go/src/net/tcpsock_posix.go:61 +0xde
        net.(*sysDialer).dialSingle(0xc0007ce000, 0x19d5a58, 0xc0006560c0, 0x19cdaf0, 0xc0005a2c90, 0x0, 0x0, 0x0, 0x0)
        	C:/Program Files/Go/src/net/dial.go:580 +0x5e8
        net.(*sysDialer).dialSerial(0xc0007ce000, 0x19d5a58, 0xc0006560c0, 0xc000b982c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        	C:/Program Files/Go/src/net/dial.go:548 +0x16b
        net.(*Dialer).DialContext(0xc000671078, 0x19d5a58, 0xc0006560c0, 0x18d345c, 0x3, 0xc0002920b0, 0xf, 0x0, 0x0, 0x0, ...)
        	C:/Program Files/Go/src/net/dial.go:425 +0x705
        google.golang.org/grpc/internal/transport.proxyDial(0x19d5a58, 0xc0006560c0, 0xc0002920b0, 0xf, 0x18dbd3c, 0xe, 0xf3eb89, 0xc000b982a0, 0x10, 0x10)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/proxy.go:125 +0x105
        google.golang.org/grpc/internal/transport.dial(0x19d5a58, 0xc0006560c0, 0x0, 0xc0002920b0, 0xf, 0xc0002920b0, 0xf, 0x0, 0x0, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/http2_client.go:160 +0x338
        google.golang.org/grpc/internal/transport.newHTTP2Client(0x19d5a58, 0xc0006560c0, 0x19d59e8, 0xc00028a340, 0xc0002920b0, 0xf, 0xc0002920b0, 0xf, 0x0, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/http2_client.go:193 +0x17a
        google.golang.org/grpc/internal/transport.NewClientTransport(...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/transport.go:579
        google.golang.org/grpc.(*addrConn).createTransport(0xc0002c4000, 0xc0002920b0, 0xf, 0xc0002920b0, 0xf, 0x0, 0x0, 0x0, 0x0, 0x18dbd3c, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1322 +0x411
        google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc0002c4000, 0xc00028a3c0, 0x1, 0x1, 0xc0181a7db9514d3c, 0x4e83dbf0d, 0x1ea6b00, 0x19de448, 0xc000244540, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1252 +0x36c
        google.golang.org/grpc.(*addrConn).resetTransport(0xc0002c4000)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1167 +0x285
        created by google.golang.org/grpc.(*addrConn).connect
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:843 +0x13b
        
         Goroutine 848 in state select, with net.(*netFD).connect.func2 on top of the stack:
        goroutine 848 [select]:
        net.(*netFD).connect.func2(0x19d5a58, 0xc000841b00, 0xc0002a4280, 0xc00064ee40)
        	C:/Program Files/Go/src/net/fd_windows.go:95 +0x8e
        created by net.(*netFD).connect
        	C:/Program Files/Go/src/net/fd_windows.go:94 +0x1e5
        
         Goroutine 44 in state select, with google.golang.org/grpc.(*ccBalancerWrapper).watcher on top of the stack:
        goroutine 44 [select]:
        google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000326480)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/balancer_conn_wrappers.go:69 +0xbb
        created by google.golang.org/grpc.newCCBalancerWrapper
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/balancer_conn_wrappers.go:60 +0x17a
        
         Goroutine 45 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
        goroutine 45 [IO wait]:
        internal/poll.runtime_pollWait(0x1e1668464d8, 0x77, 0x19c8220)
        	C:/Program Files/Go/src/runtime/netpoll.go:222 +0x65
        internal/poll.(*pollDesc).wait(0xc0002461b8, 0x77, 0xc0002a8000, 0x0, 0x0)
        	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
        internal/poll.execIO(0xc0002460e8, 0x1908fa8, 0x20, 0xc00031ac00, 0x10c03e5)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x113
        internal/poll.(*FD).ConnectEx(0xc000246000, 0x19c7380, 0xc00029e060, 0xc000288c00, 0xc000246000)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:800 +0x6a
        net.(*netFD).connect(0xc000246000, 0x19d5a58, 0xc000288c00, 0x0, 0x0, 0x19c7380, 0xc00029e060, 0x0, 0x0, 0x0, ...)
        	C:/Program Files/Go/src/net/fd_windows.go:106 +0x210
        net.(*netFD).dial(0xc000246000, 0x19d5a58, 0xc000288c00, 0x19d9a38, 0x0, 0x19d9a38, 0xc000e04090, 0x0, 0x1ef7010, 0x10)
        	C:/Program Files/Go/src/net/sock_posix.go:149 +0x112
        net.socket(0x19d5a58, 0xc000288c00, 0x18d345c, 0x3, 0x2, 0x1, 0x0, 0x0, 0x19d9a38, 0x0, ...)
        	C:/Program Files/Go/src/net/sock_posix.go:70 +0x1f0
        net.internetSocket(0x19d5a58, 0xc000288c00, 0x18d345c, 0x3, 0x19d9a38, 0x0, 0x19d9a38, 0xc000e04090, 0x1, 0x0, ...)
        	C:/Program Files/Go/src/net/ipsock_posix.go:141 +0x170
        net.(*sysDialer).doDialTCP(0xc000328280, 0x19d5a58, 0xc000288c00, 0x0, 0xc000e04090, 0x17ce980, 0x1ef6cf0, 0x0)
        	C:/Program Files/Go/src/net/tcpsock_posix.go:65 +0xc9
        net.(*sysDialer).dialTCP(0xc000328280, 0x19d5a58, 0xc000288c00, 0x0, 0xc000e04090, 0xc000b62d88, 0xf35de5, 0x60)
        	C:/Program Files/Go/src/net/tcpsock_posix.go:61 +0xde
        net.(*sysDialer).dialSingle(0xc000328280, 0x19d5a58, 0xc000288c00, 0x19cdaf0, 0xc000e04090, 0x0, 0x0, 0x0, 0x0)
        	C:/Program Files/Go/src/net/dial.go:580 +0x5e8
        net.(*sysDialer).dialSerial(0xc000328280, 0x19d5a58, 0xc000288c00, 0xc0000731b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        	C:/Program Files/Go/src/net/dial.go:548 +0x16b
        net.(*Dialer).DialContext(0xc000b63078, 0x19d5a58, 0xc000288c00, 0x18d345c, 0x3, 0xc00024a3d0, 0xf, 0x0, 0x0, 0x0, ...)
        	C:/Program Files/Go/src/net/dial.go:425 +0x705
        google.golang.org/grpc/internal/transport.proxyDial(0x19d5a58, 0xc000288c00, 0xc00024a3d0, 0xf, 0x18dbd3c, 0xe, 0xf3eb89, 0xc000073190, 0x10, 0x10)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/proxy.go:125 +0x105
        google.golang.org/grpc/internal/transport.dial(0x19d5a58, 0xc000288c00, 0x0, 0xc00024a3d0, 0xf, 0xc00024a3d0, 0xf, 0x0, 0x0, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/http2_client.go:160 +0x338
        google.golang.org/grpc/internal/transport.newHTTP2Client(0x19d5a58, 0xc000288c00, 0x19d59e8, 0xc000326380, 0xc00024a3d0, 0xf, 0xc00024a3d0, 0xf, 0x0, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/http2_client.go:193 +0x17a
        google.golang.org/grpc/internal/transport.NewClientTransport(...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/transport.go:579
        google.golang.org/grpc.(*addrConn).createTransport(0xc00036c2c0, 0xc00024a3d0, 0xf, 0xc00024a3d0, 0xf, 0x0, 0x0, 0x0, 0x0, 0x18dbd3c, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1322 +0x411
        google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc00036c2c0, 0xc000326400, 0x1, 0x1, 0xc0181a7db9514d3c, 0x4e83dbf0d, 0x1ea6b00, 0x19de448, 0xc000522000, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1252 +0x36c
        google.golang.org/grpc.(*addrConn).resetTransport(0xc00036c2c0)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1167 +0x285
        created by google.golang.org/grpc.(*addrConn).connect
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:843 +0x13b
        
         Goroutine 99 in state select, with google.golang.org/grpc.(*ccBalancerWrapper).watcher on top of the stack:
        goroutine 99 [select]:
        google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000326940)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/balancer_conn_wrappers.go:69 +0xbb
        created by google.golang.org/grpc.newCCBalancerWrapper
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/balancer_conn_wrappers.go:60 +0x17a
        
         Goroutine 100 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
        goroutine 100 [IO wait]:
        internal/poll.runtime_pollWait(0x1e1668463f0, 0x77, 0x19c8220)
        	C:/Program Files/Go/src/runtime/netpoll.go:222 +0x65
        internal/poll.(*pollDesc).wait(0xc0006c2bb8, 0x77, 0xc000486000, 0x0, 0x0)
        	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
        internal/poll.execIO(0xc0006c2ae8, 0x1908fa8, 0x20, 0xc00031b680, 0x10c03e5)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x113
        internal/poll.(*FD).ConnectEx(0xc0006c2a00, 0x19c7380, 0xc000638020, 0xc00046b1a0, 0xc0006c2a00)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:800 +0x6a
        net.(*netFD).connect(0xc0006c2a00, 0x19d5a58, 0xc00046b1a0, 0x0, 0x0, 0x19c7380, 0xc000638020, 0x0, 0x0, 0x0, ...)
        	C:/Program Files/Go/src/net/fd_windows.go:106 +0x210
        net.(*netFD).dial(0xc0006c2a00, 0x19d5a58, 0xc00046b1a0, 0x19d9a38, 0x0, 0x19d9a38, 0xc0009ce600, 0x0, 0x1ef7010, 0x10)
        	C:/Program Files/Go/src/net/sock_posix.go:149 +0x112
        net.socket(0x19d5a58, 0xc00046b1a0, 0x18d345c, 0x3, 0x2, 0x1, 0x0, 0x0, 0x19d9a38, 0x0, ...)
        	C:/Program Files/Go/src/net/sock_posix.go:70 +0x1f0
        net.internetSocket(0x19d5a58, 0xc00046b1a0, 0x18d345c, 0x3, 0x19d9a38, 0x0, 0x19d9a38, 0xc0009ce600, 0x1, 0x0, ...)
        	C:/Program Files/Go/src/net/ipsock_posix.go:141 +0x170
        net.(*sysDialer).doDialTCP(0xc00088e280, 0x19d5a58, 0xc00046b1a0, 0x0, 0xc0009ce600, 0x17ce980, 0x1ef6cf0, 0x0)
        	C:/Program Files/Go/src/net/tcpsock_posix.go:65 +0xc9
        net.(*sysDialer).dialTCP(0xc00088e280, 0x19d5a58, 0xc00046b1a0, 0x0, 0xc0009ce600, 0xc000b5ad88, 0xf35de5, 0x60)
        	C:/Program Files/Go/src/net/tcpsock_posix.go:61 +0xde
        net.(*sysDialer).dialSingle(0xc00088e280, 0x19d5a58, 0xc00046b1a0, 0x19cdaf0, 0xc0009ce600, 0x0, 0x0, 0x0, 0x0)
        	C:/Program Files/Go/src/net/dial.go:580 +0x5e8
        net.(*sysDialer).dialSerial(0xc00088e280, 0x19d5a58, 0xc00046b1a0, 0xc000e141d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        	C:/Program Files/Go/src/net/dial.go:548 +0x16b
        net.(*Dialer).DialContext(0xc000b5b078, 0x19d5a58, 0xc00046b1a0, 0x18d345c, 0x3, 0xc000310290, 0xf, 0x0, 0x0, 0x0, ...)
        	C:/Program Files/Go/src/net/dial.go:425 +0x705
        google.golang.org/grpc/internal/transport.proxyDial(0x19d5a58, 0xc00046b1a0, 0xc000310290, 0xf, 0x18dbd3c, 0xe, 0xf3eb89, 0xc000e141b0, 0x10, 0x10)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/proxy.go:125 +0x105
        google.golang.org/grpc/internal/transport.dial(0x19d5a58, 0xc00046b1a0, 0x0, 0xc000310290, 0xf, 0xc000310290, 0xf, 0x0, 0x0, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/http2_client.go:160 +0x338
        google.golang.org/grpc/internal/transport.newHTTP2Client(0x19d5a58, 0xc00046b1a0, 0x19d59e8, 0xc000326840, 0xc000310290, 0xf, 0xc000310290, 0xf, 0x0, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/http2_client.go:193 +0x17a
        google.golang.org/grpc/internal/transport.NewClientTransport(...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/transport.go:579
        google.golang.org/grpc.(*addrConn).createTransport(0xc00036c580, 0xc000310290, 0xf, 0xc000310290, 0xf, 0x0, 0x0, 0x0, 0x0, 0x18dbd3c, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1322 +0x411
        google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc00036c580, 0xc0003268c0, 0x1, 0x1, 0xc0181a7db9514d3c, 0x4e83dbf0d, 0x1ea6b00, 0x19de448, 0xc000458000, 0x0, ...)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1252 +0x36c
        google.golang.org/grpc.(*addrConn).resetTransport(0xc00036c580)
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:1167 +0x285
        created by google.golang.org/grpc.(*addrConn).connect
        	C:/Users/danil/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:843 +0x13b
        
         Goroutine 798 in state select, with net.(*netFD).connect.func2 on top of the stack:
        goroutine 798 [select]:
        net.(*netFD).connect.func2(0x19d5a58, 0xc00046b1a0, 0xc0006c2a00, 0xc000128900)
        	C:/Program Files/Go/src/net/fd_windows.go:95 +0x8e
        created by net.(*netFD).connect
        	C:/Program Files/Go/src/net/fd_windows.go:94 +0x1e5
        ]

</details>

**Comment by d-uzlov** [comment]
I didn't check if any other tests in the repository behave this same way.

**Comment by d-uzlov** [comment]
I think this issue is actually invalid, because the correct syntax to call tests in sequence would be the following:
```go
func Test(t *testing.T) {
	t.Run("", TestNSMGR_HealEndpoint)
	t.Run("", TestNSMGR_HealEndpoint)
}
```
This way everything works.
